<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = DB::table('categories')
            ->pluck('id', 'category_name');

        $products = [
            [
                'product_name' => 'Shell Rimula R4 X',
                'brand' => 'Shell',
                'category' => 'Diesel Oil',
                'api' => 'CI-4',
                'base_oil' => 'Mineral',
                'unit' => 'liter',
                'package_size' => '1L',
                'unit_price' => 350.00,
                'reorder_level' => 20,
                'status' => 'active',
            ],
            [
                'product_name' => 'Shell Rimula R4 X 5L',
                'brand' => 'Shell',
                'category' => 'Diesel Oil',
                'api' => 'CI-4',
                'base_oil' => 'Mineral',
                'unit' => 'pail',
                'package_size' => '5L',
                'unit_price' => 1650.00,
                'reorder_level' => 10,
                'status' => 'active',
            ],
            [
                'product_name' => 'Shell Rimula R5 E',
                'brand' => 'Shell',
                'category' => 'Diesel Oil',
                'api' => 'CH-4',
                'base_oil' => 'Synthetic Technology',
                'unit' => 'liter',
                'package_size' => '1L',
                'unit_price' => 420.00,
                'reorder_level' => 15,
                'status' => 'active',
            ],
            [
                'product_name' => 'Shell Helix HX5',
                'brand' => 'Shell',
                'category' => 'Gasoline Oil',
                'api' => 'API SN',
                'base_oil' => 'Mineral',
                'unit' => 'liter',
                'package_size' => '1L',
                'unit_price' => 390.00,
                'reorder_level' => 20,
                'status' => 'active',
            ],
            [
                'product_name' => 'Caltex Delo Gold',
                'brand' => 'Caltex',
                'category' => 'Diesel Oil',
                'api' => 'CI-4',
                'base_oil' => 'Mineral',
                'unit' => 'liter',
                'package_size' => '1L',
                'unit_price' => 360.00,
                'reorder_level' => 20,
                'status' => 'active',
            ],
            [
                'product_name' => 'Caltex Havoline',
                'brand' => 'Caltex',
                'category' => 'Gasoline Oil',
                'api' => 'API SN',
                'base_oil' => 'Synthetic Blend',
                'unit' => 'liter',
                'package_size' => '1L',
                'unit_price' => 410.00,
                'reorder_level' => 15,
                'status' => 'active',
            ],
            [
                'product_name' => 'Mobil Delvac MX',
                'brand' => 'Mobil',
                'category' => 'Diesel Oil',
                'api' => 'CI-4',
                'base_oil' => 'Mineral',
                'unit' => 'liter',
                'package_size' => '1L',
                'unit_price' => 380.00,
                'reorder_level' => 20,
                'status' => 'active',
            ],
            [
                'product_name' => 'Mobil Delvac 1',
                'brand' => 'Mobil',
                'category' => 'Diesel Oil',
                'api' => 'CK-4',
                'base_oil' => 'Full Synthetic',
                'unit' => 'liter',
                'package_size' => '1L',
                'unit_price' => 650.00,
                'reorder_level' => 10,
                'status' => 'active',
            ],
            [
                'product_name' => 'Castrol GTX',
                'brand' => 'Castrol',
                'category' => 'Gasoline Oil',
                'api' => 'API SP',
                'base_oil' => 'Mineral',
                'unit' => 'liter',
                'package_size' => '1L',
                'unit_price' => 430.00,
                'reorder_level' => 20,
                'status' => 'active',
            ],
            [
                'product_name' => 'Petron Rev-X',
                'brand' => 'Petron',
                'category' => 'Engine Oil',
                'api' => 'API SN',
                'base_oil' => 'Mineral',
                'unit' => 'liter',
                'package_size' => '1L',
                'unit_price' => 330.00,
                'reorder_level' => 20,
                'status' => 'active',
            ],
            [
                'product_name' => 'Hydraulic Oil ISO 46',
                'brand' => 'Industrial',
                'category' => 'Hydraulic Oil',
                'api' => null,
                'base_oil' => 'Mineral',
                'unit' => 'liter',
                'package_size' => '1L',
                'unit_price' => 290.00,
                'reorder_level' => 15,
                'status' => 'active',
            ],
            [
                'product_name' => 'Hydraulic Oil ISO 68',
                'brand' => 'Industrial',
                'category' => 'Hydraulic Oil',
                'api' => null,
                'base_oil' => 'Mineral',
                'unit' => 'liter',
                'package_size' => '1L',
                'unit_price' => 310.00,
                'reorder_level' => 15,
                'status' => 'active',
            ],
            [
                'product_name' => 'Gear Oil 80W-90',
                'brand' => 'Industrial',
                'category' => 'Gear Oil',
                'api' => 'GL-5',
                'base_oil' => 'Mineral',
                'unit' => 'liter',
                'package_size' => '1L',
                'unit_price' => 320.00,
                'reorder_level' => 15,
                'status' => 'active',
            ],
            [
                'product_name' => 'Gear Oil 85W-140',
                'brand' => 'Industrial',
                'category' => 'Gear Oil',
                'api' => 'GL-5',
                'base_oil' => 'Mineral',
                'unit' => 'liter',
                'package_size' => '1L',
                'unit_price' => 340.00,
                'reorder_level' => 15,
                'status' => 'active',
            ],
            [
                'product_name' => 'ATF Dexron III',
                'brand' => 'Industrial',
                'category' => 'Transmission Fluid',
                'api' => null,
                'base_oil' => 'Synthetic Blend',
                'unit' => 'liter',
                'package_size' => '1L',
                'unit_price' => 450.00,
                'reorder_level' => 15,
                'status' => 'active',
            ],
            [
                'product_name' => 'Brake Fluid DOT 3',
                'brand' => 'Industrial',
                'category' => 'Brake Fluid',
                'api' => null,
                'base_oil' => null,
                'unit' => 'bottle',
                'package_size' => '500ml',
                'unit_price' => 180.00,
                'reorder_level' => 20,
                'status' => 'active',
            ],
            [
                'product_name' => 'Lithium Grease EP2',
                'brand' => 'Industrial',
                'category' => 'Grease',
                'api' => null,
                'base_oil' => 'Mineral',
                'unit' => 'kg',
                'package_size' => '1kg',
                'unit_price' => 280.00,
                'reorder_level' => 10,
                'status' => 'active',
            ],
            [
                'product_name' => 'Multipurpose Grease',
                'brand' => 'Industrial',
                'category' => 'Grease',
                'api' => null,
                'base_oil' => 'Mineral',
                'unit' => 'kg',
                'package_size' => '1kg',
                'unit_price' => 250.00,
                'reorder_level' => 10,
                'status' => 'active',
            ],
            [
                'product_name' => 'Long Life Coolant',
                'brand' => 'Industrial',
                'category' => 'Coolant',
                'api' => null,
                'base_oil' => null,
                'unit' => 'liter',
                'package_size' => '1L',
                'unit_price' => 300.00,
                'reorder_level' => 15,
                'status' => 'active',
            ],
            [
                'product_name' => 'Industrial Lubricant ISO 220',
                'brand' => 'Industrial',
                'category' => 'Industrial Lubricants',
                'api' => null,
                'base_oil' => 'Mineral',
                'unit' => 'liter',
                'package_size' => '1L',
                'unit_price' => 520.00,
                'reorder_level' => 10,
                'status' => 'inactive',
            ],
        ];

        foreach ($products as $product) {
            DB::table('products')->insert([
                'product_name' => $product['product_name'],
                'brand' => $product['brand'],
                'category_id' => $categories[$product['category']],
                'api' => $product['api'],
                'base_oil' => $product['base_oil'],
                'unit' => $product['unit'],
                'package_size' => $product['package_size'],
                'unit_price' => $product['unit_price'],
                'reorder_level' => $product['reorder_level'],
                'status' => $product['status'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}